### ISSUE TITLE
Allow changing the event on which validations fires

### ISSUE THREAD

**Issue by pkasperski** [heilhead/react-bootstrap-validation#1]
Could you please add some functionality to allow changing the event, on which the validation will fire. Instead of `onChange` on input element, it should also be possible to use `onBlur`, `onFocus` and so on.

**Comment by heilhead** [comment]
Yes, I wanted to do something like. Thank you for your pull request, it's missing some parts, but I'll merge and do the rest. Feature should be available in the next release.

**Comment by pkasperski** [comment]
I’ve seen you have merged my changes, Thanks!  

Do you also think there is a way to show field error message only onBlur instead of onChange, also it would be great for this to be a configuration option.

**Comment by heilhead** [comment]
I've published the latest version (0.1.7) to npm. It includes the changes from your pull request. Please test and let me know if it does not work as expected.

> Do you also think there is a way to show field error message only onBlur instead of onChange

Not sure I understand. You want to show error message independently of validation event, i.e. set validation to `onChange`, but error message to `onBlur`?

**Comment by heilhead** [comment]
Also, final property name is [`validationEvent`](https://github.com/heilhead/react-bootstrap-validation#validationevent-string).

**Comment by pkasperski** [comment]
> Not sure I understand. You want to show error message independently of validation event, i.e. set validation to onChange, but error message to onBlur?

Yup, I think that it would be nice not to confuse the user with an error when he didn't finish his typing. (for example email field).

Another example would be:
- validation is on `onBlur` so error message would be shown only when the field loses focus
- user types something invalid and moves to another field
- validation fires and the error for that field is shown
- user goes back and fixes the typo, error message still says on (and it should disappear when the field is valid)

**Comment by heilhead** [comment]
I see your point and will think about it. Thanks.

**Comment by oscar-g** [comment]
@heilhead Is it possible to have multiple validation events in the same attribute?
`validationEvent="onBlur,onChange"`

**Comment by heilhead** [comment]
@oscar-g Currently it is impossible.
