### ISSUE TITLE
disable submit button until form is valid

### ISSUE THREAD

**Issue by LoicUV** [heilhead/react-bootstrap-validation#10]
Is there a simple way to disable the submit button of the form when the form is invalid ?

**Comment by LoicUV** [comment]
As I only had one input in my form I used a state variable I changed in the validate method of that input.

**Comment by heilhead** [comment]
There's no way to do this currently, but I plan on adding additional callbacks to form element to make this possible.

**Comment by camsjams** [comment]
In the meantime - are there any methods available to accomplish this?

**Comment by camsjams** [comment]
@heilhead my colleague @JasonTsao made a very slight PR change for this feature, can you take a look and merge in if you approve?

https://github.com/heilhead/react-bootstrap-validation/pull/42/files

Also might be relevant to you @LoicUV if you are still interested.
