### ISSUE TITLE
Only child exception when using react-boostrap tooltip inside Form

### ISSUE THREAD

**Issue by LoicUV** [heilhead/react-bootstrap-validation#14]
``` javascript
(...)
<Form>
    <OverlayTrigger placement="right" overlay={tooltip}>
        <Button bsStyle="default">Holy guacamole!</Button>
     </OverlayTrigger>
    (...)
</Form>
```

`Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.`

Works when `OverlayTrigger` is placed outside of `<Form>` component. My guess is that it has something to do with `Form` cloning its children when rendering, but can't pinpoint the exact location of the issue. Any idea ?

**Comment by heilhead** [comment]
Thanks for the report. I'll look into it.
