### ISSUE TITLE
errorHelp prop passed in as object breaks in React 0.14.3

### ISSUE THREAD

**Issue by camerow** [heilhead/react-bootstrap-validation#23]
You can no longer pass in objects as arguments to the errorHelp prop. React throws the following error: 

`Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {required}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `ValidatedInput`.`

The following works:
`errorHelp={'Please enter a phone number' }`

This does not:
`errorHelp={{ required:'Please enter a phone number' }}`

**Comment by camerow** [comment]
Ok, here's the helpful comment. As far as I know - as of React v0.14.3 you need to use "react-addons-create-fragment": https://facebook.github.io/react/docs/create-fragment.html

`var createFragment = require('react-addons-create-fragment');
...
errorHelp={ createFragment({ required:'Please enter a phone number' }) }`

**Comment by LoicUV** [comment]
Thx that helped me. It does break the propTypes validation of `errorHelp` though, which is either `string` or `object`.

**Comment by camerow** [comment]
Yeah, sorry I figured that out later, but found this while at work so was a bit distracted.

**Comment by marcelpanse** [comment]
The workaround doesn't work if you do something like 
`errorHelp={createFragment({required: this.txt['email-required'], isEmail: this.txt['email-invalid']})}`

Then both strings are shown when the validation fails.

@heilhead this totally breaks the library, what is the proper way to fix this?

**Comment by marcelpanse** [comment]
I created a PR https://github.com/heilhead/react-bootstrap-validation/pull/37 to fix this problem, can you merge this please and publish it to npm? 

I the meanwhile as a workaround while this isn't merged and published, you can reference my fork directly in your package.json: 
`"react-bootstrap-validation": "git+https://github.com/marcelpanse/react-bootstrap-validation#dist"`

**Comment by marcelpanse** [comment]
@heilhead can you also publish this to NPM so we can actually use it?

**Comment by heilhead** [comment]
Sorry, wanted to thoroughly test before publishing to NPM, but did not have
time. Hopefully will do it this week.
