### ISSUE TITLE
How to validate input  with pattern?

### ISSUE THREAD

**Issue by anilapu** [heilhead/react-bootstrap-validation#3]
In my form I want to add pattern validation. How can I achieve this?
If you make a list of validate attribute options in readme file it will be helpful.

**Comment by lemonCMS** [comment]
Like so.

``` javascript
validate={(v,obj)=>{
  var re = /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/;
  return !Validator.isNull(v) && re.test(v);;
}}
```

**Comment by heilhead** [comment]
Yes, you should use callback function to validate the value as @lemonCMS showed.
