### ISSUE TITLE
HTML5 attributes?

### ISSUE THREAD

**Issue by TheSharpieOne** [heilhead/react-bootstrap-validation#34]
Any thoughts on using HTML5 attributes to determine validation? Such as the required attribute to trigger the required validation, min, max, min-length, max-length, pattern etc.. and type values trigger other validation, type="email" to trigger email validation, date, tel, number, url, etc...

If using the HTML5 validation attributes to determine the validation isn't wanted, how about using the validation schema to add HTML5 validation attributes?

Why am I obsessed with the HTML5 validation attribute? Accessibility, that's why. The HTML5 attributes are standards, which means assistive technology (such as screen readers) know what do to when they come across the attributes. The assistive technology will present the form field differently, letting the user know that it are required, an email address, has a minimum length or anything that would prevent the field from being valid.

Yes, I could add both the HTML5 attributes and the validation attribute/schema... but that is double the work and components are supposed to make everything easier :D

**Comment by mikethejet** [comment]
how about autocomplete that browser will ask to save login credentals like any ordinary html form?
