### ISSUE TITLE
Default props className to form-horizontal

### ISSUE THREAD

**Issue by LoicUV** [heilhead/react-bootstrap-validation#5]
Why do you default the Form className to form-horizontal ?

```
Form.defaultProps = {
    model: {},
    className: 'form-horizontal',
    validationEvent: 'onChange',
    onInvalidSubmit: function onInvalidSubmit() {}
};
```

**Comment by heilhead** [comment]
Adding default classname was an oversight.

As for you PR #6, I'll do some testing to see if removing `action` prop has any side effects and will merge it tomorrow.

Thanks!

**Comment by LoicUV** [comment]
Alright thanks.
As for the action prop, you could default it when it's not passed as a prop.
