### ISSUE TITLE
Some problems with entered data in the middle of text

### ISSUE THREAD

**Issue by volodimirian** [heilhead/react-bootstrap-validation#62]
I have a vlidatedInput with text type. I enter some text into this field. 
And when I move cursor in begining of the string on in the middle of the string and enter some text after every character cursor moves to end of the string.

Could you help me to solve this problem or may be somebody knows about this trouble?

If it is neccessary any additional information, I'll provide it. Tell me what needed.

Thanks

**Comment by volodimirian** [comment]
I found that it is my bug in my realisation not in plugin.

**Comment by arturohernandez10** [comment]
@volodimirian I need to correct this bug in an existing project. Any insight into how this could happen will be appreciated.
