### ISSUE TITLE
Input bootstrap element is deprecated

### ISSUE THREAD

**Issue by plemarquand** [heilhead/react-bootstrap-validation#65]
`<Input>` has been deprecated in favour of `<FormControl>`

ValidatedInput should be using FormControl.

**Comment by camsjams** [comment]
+1

**Comment by boriswexler** [comment]
@jgautheron Would you consider publishing your fork to npm? It seems to contain all the latest updates - and I don't think this package is maintained anymore. Thanks!

**Comment by jgautheron** [comment]
@boriswexler  Actually it didn't work out for me so I used `redux-form` 5.x, works fine with `react-bootstrap`.
