### ISSUE TITLE
Validator aqainst input

### ISSUE THREAD

**Issue by lemonCMS** [heilhead/react-bootstrap-validation#7]
I would like to see a validate function somethin in the terms of 

```
equalsInput:inputname
```

This way it would be possible to check if fields are valid against another field, like "password" and "password again" fields.

I believe this is not possible with a simple Validator.extend 

I hope this is possible...

**Comment by heilhead** [comment]
As I demonstrated in the docs, you can do it this way:

``` javascript
<ValidatedInput
    type='password'
    name='password-confirm'
    label='Confirm Password'
    // Validate can be a function
    validate={(val, context) => val === context.password}
    errorHelp='Passwords do not match'
/>
```

`context` in the callback is an object containing all form values
